export const UNIT_ICONS: Record<string, string> = {
  infantry: '🚶',
  mech_infantry: '🏃',
  tank: '🛡️',
  artillery: '💥',
  anti_air: '🎯',
  marine: '⚓',
  guards: '🛡',
  raider: '⚡',
  guerrilla: '🌿',
  partisan: '🗡',
  fighter: '✈️',
  bomber: '🛩️',
  battleship: '🚢',
  carrier: '🛳️',
  cruiser: '⛵',
  destroyer: '🚤',
  submarine: '🐋',
  transport: '📦',
};
